### ISSUE TITLE
Could not load type 'Bybit.Api.BybitApiAddresses'

### ISSUE THREAD

**Issue by ThomasJaeger** [burakoner/Bybit.Api#7]
I'm getting error Could not load type 'Bybit.Api.BybitApiAddresses' after I upgraded from version 1.3.0 to the latest version 2.4.0.

`System.TypeLoadException: Could not load type 'Bybit.Api.BybitApiAddresses' from assembly 'Bybit.Api, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null'.
   at ExchangeBybit.Api.Configure(Boolean production, String bybitKey, String bybitSecret)
   at ExchangeBybit.Api..ctor(Boolean production, String bybitKey, String bybitSecret) in /../ExchangeBybit/Api.cs:line 26
   at Bybit.BybitBrokerV2..ctor(IDatabase db) in /..BybitBrokerV2.cs:line 86
   at BotService.Worker.StartBot(CancellationToken cancellationToken) in /../Worker.cs:line 149
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Program.<Main>$(String[] args) in /home/hampelman/source/jtrading/BotService/Program.cs:line 9
   at Program.<Main>(String[] args)`

How can I fix this? Any help would be appreciate it. Thank you!

**Comment by ThomasJaeger** [comment]
There were breaking changes and had to adjust. Still working on updating all breaking changes. :-(

**Comment by burakoner** [comment]
Bybit.Api doesnt has Bybit.Api.BybitApiAddresses class. It's related with your codes. You may want to take a look for Bybit.Api.BybitApiAddress class
